import { ReactNode } from 'react';

interface ReportLayoutProps {
  title: string;
  subtitle?: string;
  reportingDate: string;
  children: ReactNode;
}

export function ReportLayout({ title, subtitle, reportingDate, children }: ReportLayoutProps) {
  return (
    <div className="report-root bg-white text-gray-900 min-h-screen">
      {/* Print-optimized styles */}
      <style>{`
        @media print {
          @page { margin: 20mm 15mm; size: A4 portrait; }
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .report-root { font-size: 10pt; line-height: 1.5; }
          .no-print { display: none !important; }
          .page-break { page-break-before: always; }
          .avoid-break { page-break-inside: avoid; }
          table { font-size: 9pt; }
        }
        @media screen {
          .report-root { max-width: 900px; margin: 0 auto; padding: 40px 32px; }
        }
        .report-root table { border-collapse: collapse; width: 100%; }
        .report-root th, .report-root td { 
          padding: 6px 10px; 
          text-align: left; 
          border-bottom: 1px solid #e5e7eb; 
          font-size: 0.8125rem;
        }
        .report-root th { 
          font-weight: 600; 
          font-size: 0.6875rem;
          text-transform: uppercase; 
          letter-spacing: 0.05em;
          color: #6b7280; 
          background: #f9fafb;
          border-bottom: 2px solid #d1d5db;
        }
        .report-root td.num { text-align: right; font-variant-numeric: tabular-nums; }
        .report-root th.num { text-align: right; }
        .report-root .section { margin-bottom: 28px; }
        .report-root .section-title { 
          font-size: 0.75rem; 
          font-weight: 600; 
          text-transform: uppercase; 
          letter-spacing: 0.08em;
          color: #059669; 
          margin-bottom: 10px;
          padding-bottom: 6px;
          border-bottom: 2px solid #059669;
        }
        .report-root .metric-grid { 
          display: grid; 
          grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); 
          gap: 12px; 
          margin-bottom: 16px;
        }
        .report-root .metric-card {
          padding: 12px;
          border: 1px solid #e5e7eb;
          border-radius: 6px;
          background: #f9fafb;
        }
        .report-root .metric-label { font-size: 0.6875rem; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
        .report-root .metric-value { font-size: 1.25rem; font-weight: 700; font-variant-numeric: tabular-nums; color: #111827; }
        .report-root .metric-unit { font-size: 0.75rem; color: #6b7280; margin-left: 4px; }
        .report-root .disclaimer {
          font-size: 0.6875rem;
          color: #9ca3af;
          border-top: 1px solid #e5e7eb;
          padding-top: 12px;
          margin-top: 24px;
          line-height: 1.6;
        }
        .report-root .bar-fill {
          height: 8px;
          border-radius: 4px;
          background: #059669;
        }
        .report-root .bar-bg {
          height: 8px;
          border-radius: 4px;
          background: #e5e7eb;
          width: 100%;
        }
      `}</style>

      {/* Cover / Header */}
      <header className="mb-10">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">{title}</h1>
            {subtitle && <p className="text-sm text-gray-500 mt-1">{subtitle}</p>}
          </div>
          <div className="text-right">
            <p className="text-xs text-gray-400 uppercase tracking-wider">Reporting Date</p>
            <p className="text-sm font-semibold tabular-nums">{reportingDate}</p>
          </div>
        </div>
        <div className="h-1 bg-gradient-to-r from-emerald-600 to-blue-600 rounded-full" />
      </header>

      {/* Report Content */}
      {children}

      {/* Footer */}
      <footer className="disclaimer">
        <p><strong>Disclaimer:</strong> This report is generated from BondDB and contains data aggregated from issuer-reported sources. 
        Impact KPIs are based on methodologies disclosed by issuers and may not be directly comparable across instruments. 
        SDG mapping reflects issuer-reported use-of-proceeds allocation. Coverage indicators note whether data is reported, estimated, or missing. 
        This report does not constitute investment advice.</p>
        <p className="mt-2">Data snapshot: {new Date().toISOString().split('T')[0]} · Generated by BondDB ESG Intelligence Platform</p>
      </footer>

      {/* Print button (screen only) */}
      <div className="no-print fixed bottom-6 right-6 flex gap-2">
        <button
          onClick={() => window.print()}
          className="px-5 py-2.5 bg-emerald-600 text-white text-sm font-medium rounded-lg shadow-lg hover:bg-emerald-700 transition-colors"
        >
          Save as PDF
        </button>
        <button
          onClick={() => window.close()}
          className="px-5 py-2.5 bg-gray-200 text-gray-700 text-sm font-medium rounded-lg shadow-lg hover:bg-gray-300 transition-colors"
        >
          Close
        </button>
      </div>
    </div>
  );
}

// Helper components for report sections
export function ReportSection({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="section avoid-break">
      <h2 className="section-title">{title}</h2>
      {children}
    </div>
  );
}

export function MetricCard({ label, value, unit }: { label: string; value: string | number; unit?: string }) {
  return (
    <div className="metric-card avoid-break">
      <p className="metric-label">{label}</p>
      <p className="metric-value">
        {value}
        {unit && <span className="metric-unit">{unit}</span>}
      </p>
    </div>
  );
}

export function PercentBar({ value, label }: { value: number; label: string }) {
  return (
    <div className="flex items-center gap-3">
      <span className="text-xs text-gray-600 w-24 shrink-0">{label}</span>
      <div className="bar-bg flex-1">
        <div className="bar-fill" style={{ width: `${Math.min(value, 100)}%` }} />
      </div>
      <span className="text-xs font-semibold tabular-nums w-10 text-right">{value.toFixed(0)}%</span>
    </div>
  );
}
